# State of the art {#sota}

## Gene Set Analysis

### Analyzing gene expression data in terms of gene sets: methodological issues (Goeman and Buhlmann)

* Theoretical Background
  * Hypothesis
  * 2x2 Table Methods
  
* Comparisons and Problems 
  * Competitive vs self-contained tests: Self-contained seems more powerful / reliable
  * Gene sampling vs subject sampling: 
    * P-Values from gene sampling seems less relevant for real application
    * Independence assumption mostly does not hold
    
### A comparison of mechanistic signaling pathway activity analysis methods (Amadoz and Dopazo)

* Mechanistic Pathway Activity (MPA) methods focus on the activity of pathway sub-structures dened in different ways.
* Biologically inspired pathway substructures like receptor-to-effector circuits and methods to score their activity are relevant for the performance of MPA methods.
* MPA can help to discover actionable mechanistic biomarkers.
    
## Pathway comparison and 
    
### Network Architecture Predisposes an Enzyme to Either Pharmacologic or Genetic Targeting

Discrepancy between chemical inhibition and genetic knockdown when it comes to network-level mechanisms
* Experimentation Methods:
  * Chemical inhibition: basic chemical compound / potential drug molecule
  * Genetic knockdown: Reduction of expression levels throug genetic modifications or substances injected into cytoplasma (e.g. RNA interference or CRISPRs)

* Main statements:
  * Negative autoregulation or feedback favors inhibitor potency, whereas positive autoregulation or feedback favors knockdown potency
  * Evidence through theoretical modeling of three-tiered enzyme cascades and in vivo experiments

### The Signaling Pathways Project: an integrated 'omics knowledgebase for mammalian cellular signaling pathways

* Example web knowledge base
  * Aims to provide informations about path-ways and smal molecules interactions
* Source Data:
  * Transcriptomic data
  * ChiP-Seq data
* Classification of data:
  * Cellular signaling pathway nodes
    * Receptors
    * Enzymes
    * Transcription factors
  * Bioactive small molecules

TFIDF: Sounds amazing but actually sucks when it comes to gene sets ... https://en.wikipedia.org/wiki/Tf–idf



